---
- name: Gatus | Render configuration YAML
  ansible.builtin.template:
    src: "templates/gatus/gatus.config.yaml.j2"
    dest: "{{ gatus_config_dir }}/config.yaml"
    owner: "{{ gitops_uid }}"
    group: "{{ gitops_gid }}"
    mode: "0644"
