---
## HOMELAB-WIDE VARIABLES
default_remote_nas_ip: "{{ hostvars['procyon'].ansible_host }}"

gitops_user: "lab"
gitops_uid: 1000
gitops_gid: 1000
gitops_tz: "America/New_York"

## ANSIBLE BUILT-IN VARIABLES
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "{{ gitops_user }}"

converge_arch: false
converge_arch_aur: false
converge_arch_desktop: false
converge_ubuntu: false
converge_docker: false
converge_node_exporter: false
converge_devops: false
converge_docker_monitoring: false
step_s3_mirror: false

git_author_name: "Allan Lewis"
git_author_email: "allan@allanshomelab.com"
