---
## HOMELAB-WIDE VARIABLES
gitops_user: "lab"
gitops_uid: 1000
gitops_gid: 1000
gitops_tz: "America/New_York"

## ANSIBLE BUILT-IN VARIABLES
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "{{ gitops_user }}"

## CONVERGENCE FEATURE FLAGS
converge_arch: false
converge_arch_aur: false
converge_arch_desktop: false
converge_ubuntu: false
converge_docker: false
converge_node_exporter: false
converge_devops: false
converge_docker_monitoring: false
converge_s3_mirror: false
converge_postgres_dump: false
converge_restore: false
converge_docker_gatus: false
converge_docker_it_tools: false
converge_docker_ngb: false
converge_openvpn: false
converge_docker_memos: false
converge_docker_portainer: false
converge_docker_nginx: false
converge_docker_vaultwarden: false

## HOMELAB-WIDE VARIABLES
default_remote_nas_ip: "{{ hostvars['procyon'].ansible_host }}"

git_author_name: "Allan Lewis"
git_author_email: "allan@allanshomelab.com"

backup_runner_remote_base_path: "/mnt/pool1/gitops-homelab/backup-runner/{{ inventory_hostname }}"
backup_runner_cron_hour: "*"
backup_runner_user: "allan"
backup_runner_remote_host: "{{ default_remote_nas_ip }}"

default_remote_nas_per_host_backup_volume: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}"
backup_restore_owner: "lab"
backup_restore_group: "lab"

