ansible_python_interpreter: /run/current-system/sw/bin/python3

converge_docker: true

dot_user: "lab"
dotfiles_dest: "/home/lab/.dotfiles"
dotfiles_repo: "https://github.com/allan-lewis/dotfiles.git"
dotfiles_version: "main"

