---
## FOR AUTHENTIK DISASTER RECOVERY TESTING
converge_docker_authentik: true
authentik_version: "2025.10.3"

## FOR IMMICH DISASTER RECOVERY TESTING
converge_docker_immich: true
immich_version: "v2.4.1"
immich_postgres_dir: "/srv/immich/postgres"
immich_redis_dir: "/srv/immich/redis"
immich_model_dir: "/srv/immich/model-cache"
immich_upload_mount: "/mnt/immich"
immich_upload_mount_nfs_path: "/mnt/pool0/immich"
