---
converge_restore: true

backup_runner_volumes: [
  {
    src: "/home/lab/backup-restore/lab",
    dest: "{{ default_remote_nas_per_host_backup_volume }}/lab",
    owner: "lab"
  },
  {
    src: "/home/lab/backup-restore/472",
    dest: "{{ default_remote_nas_per_host_backup_volume }}/472",
    owner: "472"
  },
  {
    src: "/home/lab/backup-restore/root",
    dest: "{{ default_remote_nas_per_host_backup_volume }}/root",
    owner: "root"
  }
]

