---
converge_restore: true

doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_MATURIN') }}"
doppler_config: "mat"
doppler_project: "orchestrator"

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main

s3_mirror_base_dir: "/var/lib/s3-mirror"
s3_mirror_buckets: [
  "gitops-homelab-orchestrator-disks",
  "gitops-homelab-orchestrator-haos",
  "gitops-homelab-orchestrator-tf"
]
s3_mirror_cron:
  enabled: true
  minute: "12"
  hour: "2"
  weekday: "6"

backup_runner_cron_minute: "20"
backup_runner_volumes: [
  { 
    src: "{{ s3_mirror_base_dir }}",
    dest: "{{ default_remote_nas_per_host_backup_volume }}/s3-mirror",
    owner: "root"
  }
]
