doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_ORCHESTRATOR') }}"
doppler_config: "dev"
doppler_project: "orchestrator"

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main

converge_s3_mirror: true
s3_mirror_base_dir: "/var/lib/s3-mirror"
s3_mirror_buckets: [
  "gitops-homelab-orchestrator-tf"
]

backup_runner_cron_minute: "8"
backup_runner_volumes: [
  { 
    src: "{{ s3_mirror_base_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/s3-mirror" 
  }
]
