doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_ORCHESTRATOR') }}"
doppler_config: "dev"
doppler_project: "orchestrator"

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main