doppler_service_token: "{{ lookup('env', 'DOPPLER_SERVICE_TOKEN_ORCHESTRATOR') }}"
doppler_config: "dev"
doppler_project: "orchestrator"

ansible_environment: "production"

s3_mirror_base_dir: "/var/lib/s3-mirror"
s3_mirror_buckets: [
  "gitops-homelab-longhorn",
  "gitops-homelab-longhorn-attic",
  "gitops-homelab-longhorn-staging",
  "gitops-homelab-terraform",
  "gitops-homelab-orchestrator-tf"
]
s3_mirror_cron:
  enabled: true
  minute: "0"
  hour: "8"
  weekday: "5"

backup_runner_cron_minute: "10"
backup_runner_volumes: [
  { 
    src: "{{ s3_mirror_base_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/s3-mirror" 
  }
]

source_code_repos:
  - repo: git@github.com:allan-lewis/allans-home-lab.git
    dest: allans-home-lab
    version: main
