backup_runner_cron_hour: "*"
backup_runner_cron_minute: "35"
backup_runner_healthchecks_url: "https://hc-ping.com/700f0972-2de8-40af-8561-703d0ef7910d"
backup_runner_healthchecks_status: "https://healthchecks.io/b/2/9f976a0d-58e9-4093-a41c-ca0e40981d36.json"

converge_restore: true

converge_docker_tautulli: true
tautulli_config_dir: "/etc/tautulli"

converge_docker_plex: true
plex_config_dir: "/srv/plex/config"
plex_transcode_dir: "/srv/plex/transcode"
plex_media_library: "/mnt/media-library"

converge_docker_jellyfin: true
jellyfin_config_dir: "/srv/jellyfin/config"
jellyfin_cache_dir: "/srv/jellyfin/cache"
jellyfin_media_library: "/mnt/media-library"

"backup_runner_volumes": [
  { 
    src: "{{ plex_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/plex/config" 
  },
  { 
    src: "{{ tautulli_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/tautulli/config" 
  },
  { 
    src: "{{ jellyfin_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/jellyfin/config" 
  },
  { 
    src: "/srv/immich/postgres",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/immich/postgres-volume" 
  },
  { 
    src: "{{ postgres_db_backup_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/immich/db-dumps" 
  }
]

converge_postgres_dump: true
postgres_db_container: immich_postgres
postgres_db_name: "immich"
postgres_db_user: "postgres"
postgres_db_password: "{{ lookup('env', 'IMMICH_DB_PASSWORD') }}"
postgres_db_backup_dir: /var/lib/postgres-db-dumps

