---
converge_docker_media_acquisition: true
lidarr_config_dir: "/etc/lidarr"
prowlarr_config_dir: "/etc/prowlarr"
radarr_config_dir: "/etc/radarr"
sonarr_config_dir: "/etc/sonarr"
transmission_config_dir: "/etc/transmission"
transmission_watch_dir: "/var/lib/transmission/watch"
media_acquisition_mount: "/mnt/media-acquisition"

"backup_runner_cron_minute": 50
"backup_runner_volumes": [
  { 
    src: "{{ lidarr_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/lidarr/config",
    owner: "lab"
  },
  { 
    src: "{{ prowlarr_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/prowlarr/config",
    owner: "lab"
  },
  { 
    src: "{{ radarr_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/radarr/config",
    owner: "lab"
  },
  { 
    src: "{{ sonarr_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/sonarr/config",
    owner: "lab"
  },
  { 
    src: "{{ transmission_config_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/transmission/config",
    owner: "lab"
  },
  { 
    src: "{{ transmission_watch_dir }}",
    dest: "{{ backup_runner_user }}@{{ backup_runner_remote_host }}:{{ backup_runner_remote_base_path }}/transmission/watch",
    owner: "lab"
  }
]
media_acquisition_nfs_server: "{{ default_remote_nas_ip }}"

converge_restore: true
