---
- name: restart compose stack
  listen: restart compose stack
  ansible.builtin.command: >
    docker compose up -d
    --remove-orphans
    --no-build
    {{ compose_pull_recreate | ternary('--pull always --force-recreate', '--pull missing') }}
  args:
    chdir: "{{ compose_project_dir }}"
  changed_when: false

